# Generated by Django 4.2.4 on 2023-08-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('universityId', models.IntegerField()),
                ('phoneNumber', models.IntegerField()),
                ('bloodGroup', models.TextField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
