# Generated by Django 4.2.4 on 2023-08-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_donors_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donors',
            new_name='Donor',
        ),
    ]
