# Generated by Django 4.2.4 on 2023-08-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_donors_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='bloodGroup',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
