# Generated by Django 4.2.4 on 2023-08-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_donor_bloodgroup_alter_donor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='bloodGroup',
            field=models.CharField(max_length=3),
        ),
    ]
